/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

//        Carro f = new Carro();
//
//        f.definirVelocidadeAtual(10);
//        f.definirCor("azul");
//        f.definirModelo("Fusca");
//
//        Carro g = new Carro();
//
//        g.definirVelocidadeAtual(10);
//        g.definirCor("azul");
//        g.definirModelo("Gol");
//
//        System.out.println(f.obterModelo() + " " + f.obterCor() + " está a " + f.obterVelocidade() + " km/h");
//
//        System.out.println(g.obterModelo() + " " + g.obterCor() + " está a " + g.obterVelocidade() + " km/h");


//        Caneta c = new Caneta("Vermelha" , 98);
//
//        System.out.println(c);
//        System.out.println(c.desenhar(98));
//        System.out.println(c.desenhar(-15));
//
//
//
//        Contador cont = new Contador();
//
//        cont.setValorAtual(5);
//        System.out.println(cont.getValorAtual());
//        cont.incrementarValor();
//        System.out.println(cont.getValorAtual());


        //Carro car = new Carro("Astra","Vermelho", 0 , 150);

        Estudante est = new Estudante("Gean" , 20240105 , 12635 );
        Estudante esst = new Estudante("GeanL" , 1215 , 1335 );

        System.out.println(esst.getTotal());
    }
}
