/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.sql.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        int[] moedas = new int[6];

        System.out.println("Você tem moedas no bolso ? Se sim , digite uma por uma: ");
        int moeda = scanner.nextInt();

        switch (moeda){
            case 1:
                moedas[0] ++; //moedas de 1 centavo
                break;
            case 2:
                moedas[1] ++;  //moedas de 5 centavo
                break;
                case 3:
        }

    }
}
